### ISSUE TITLE
unable to download a twitch clip

### ISSUE THREAD

**Issue by Frambooisier** [mohad12211/twitch-downloader-gui#14]
hey, tried to download this clip
https://clips.twitch.tv/ComfortableRacyNigiriHeyGuys-EDnR1IXyqG3A44X-

download faild on error:
`TwitchDownloaderCLI 1.53.0
Copyright (C) 2024 TwitchDownloaderCLI

ERROR(S):
  Required option 'o, output' is missing.

  -u, --id         Required. The ID or URL of the clip to download.

  -o, --output     Required. Path to output file.

  -q, --quality    The quality the program will attempt to download.

  --bandwidth      (Default: -1) The maximum bandwidth the clip downloader is
                   allowed to use in kibibytes per second (KiB/s), or -1 for no
                   maximum.

  --help           Display this help screen.

  --version        Display version information.
`

**Comment by mohad12211** [comment]
I have released version 3.0.0 and it's debian package, can you test if it works with `TwitchDownloaderCLI` version [1.54.0](https://github.com/lay295/TwitchDownloader/releases/tag/1.54.0)

**Comment by Frambooisier** [comment]
first I updated to 1.54.0 which did not help, then I updated GUI to 3.0.0 and now I get error of invalid clip ID

**Comment by mohad12211** [comment]
![image](https://github.com/mohad12211/twitch-downloader-gui/assets/51754973/5d7ede6a-810d-499d-b8ff-f8c4b8a5ba0c)

weird, I was able to download this clip with ubuntu 23.10
I assume it works for other clips, and it's only this clip that's not working?

**Comment by Frambooisier** [comment]
Im getting same message with any clip, now Im unsure if before I could get other clips

**Comment by mohad12211** [comment]
> how could I check which version of GUI I have installed apart from using apt info? such as --version or about section

There's none currently, I added a todo for it.
if you can see the "bandwidth limit" option in "Clip Downloader", then that's version 3.0.0.

it shouldn't matter since the actual fetching of the information didn't change in 3.0.0, I can still download the clip in 2.0.0 btw.

My only guess is that your IP got flagged for some reason?

**Comment by Frambooisier** [comment]
I tried 2 VPN connections same result it was free proton vpn USA and Netherlands

**Comment by Frambooisier** [comment]
I can download VODs but not clips, I guess if I would have problems with libcurl then I would not be able to do that?

just to make sure, this is what I have installed fro libcurl
![image](https://github.com/mohad12211/twitch-downloader-gui/assets/15931041/4ff5965c-df0f-471c-aa62-98ecf70c173d)

**Comment by Frambooisier** [comment]
I take that back, I cannot download VOD, initailly I thought I am just low on space, but /sys is something different I guess
![image](https://github.com/mohad12211/twitch-downloader-gui/assets/15931041/6673c1a4-e71d-4ecf-9769-c87e33a445f9)

**Comment by mohad12211** [comment]
the downloading is handled by `TwitchDownloaderCLI`, so is the `/sys` warning, I have a similar one with `/proc` not sure what's about it. if the download is getting stuck or not finishing, that's a `TwitchDownloaderCLI` problem and the GUI has nothing to do with it.
The GUI interacts with `libcurl` when you do `Get Info`, since you got the vod info, libcurl worked properly there.
I just downloaded Kubuntu 23.10 and I can reproduce the issue, investigating it currently...

**Comment by Frambooisier** [comment]
ok regardless that message, VOD gets downloaded at the end

**Comment by mohad12211** [comment]
Found the problem, will push a new version tomorrow.
