### ISSUE TITLE
Adjusting Download Threads count does nothing

### ISSUE THREAD

**Issue by SolarWolf-Code** [mohad12211/twitch-downloader-gui#9]
I've tested using the same Twitch VOD 3 times with varying counts (5, 10, 50). If you are using something similar to/are using StreamLink going past 10 would not work anyways. Although 5 should be slower than 10. Each resulted in the same time taken.

**Comment by SolarWolf-Code** [comment]
Looks like this issue stems from the actually [TwitchDownloaderCLI](https://github.com/lay295/TwitchDownloader) and not the Linux GUI wrapper, can safely close this issue :))

**Comment by SolarWolf-Code** [comment]
https://github.com/lay295/TwitchDownloader/issues/540#issuecomment-1424973332

**Comment by ScrubN** [comment]
I just wanted to clarify that VOD download threads are the amount of simultaneous network requests. This is useful because when the user's bandwidth is fast enough the download bottleneck becomes initializing, sending out network requests, and waiting for the header response before actually downloading the file.
You can simulate this by downloading a 160p, where the file sizes are so small a single download thread is only able to use around 4mbps.

The linked issue is asking why the 'Finalizing Video' stage is single-threaded, which is a limitation of Ffmpeg.
